services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: lmb
      POSTGRES_PASSWORD: lmb
      POSTGRES_DB: lmb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
